# #
#   @type           github workflow
#   @author         Aetherinox
#   @project        KeeWeb
#   @repo           https://github.com/keeweb/keeweb
#   @usage          run linter and build tests on repository
#
#   @secrets        secrets.CODECOV_TOKEN               CodeCov API Token (https://docs.codecov.com/reference/overview)
# #

name: 'ðŸ”¨ Build â€º Tests'
run-name: 'ðŸ”¨ Deploy â€º Tests'

# #
#   Triggers
# #

on:

    # #
    #   Trigger â€º Workflow Dispatch
    #
    #   If any values are not provided, will use fallback env variable
    # #

    workflow_dispatch:
        inputs:

            # #
            #   Name of the plugin to use when creating the release zip / exe filename
            #     e.g: keeweb-v1.0.0.zip
            # #

            PLUGIN_NAME:
                description:  "ðŸ“¦ Name of App"
                required:     true
                default:      'keeweb'
                type:         string

    # #
    #   Trigger â€º Push
    # #

    push:
        branches:
            - 'main'
            - 'master'
            - 'develop/v?[0-9]+.[0-9]+.[0-9]+'
            - 'v?[0-9]+.[0-9]+.[0-9]+'
            - '!all-contributors/**'

    # #
    #   Trigger â€º Pull Requests
    # #

    pull_request:

# #
#   Environment Vars
#
#   PLUGIN_NAME                 This is the project name used in Cloudflare.
# #

env:
    PLUGIN_NAME:            ${{ github.event.inputs.PLUGIN_NAME || 'keeweb' }}
    BOT_NAME_1:             EuropaServ
    BOT_NAME_DEPENDABOT:    dependabot[bot]

# #
#   Jobs
# #

jobs:

    # #
    #   Jobs â€º Initialize
    # #

    job-initialize:
        name: >-
            ðŸ’¡ Initialize
        runs-on: ubuntu-latest
        outputs:
            package_version: ${{ steps.task_init_pkg_ver_get.outputs.PACKAGE_VERSION }}
            guid: ${{ steps.task_init_dotenv_get.outputs.GUID }}
            uuid: ${{ steps.task_init_dotenv_get.outputs.UUID }}
        permissions:
            contents: write
            packages: write
        steps:

            # #
            #   Initialize â€º Start
            # #

            - name: 'âœ… Start'
              id: task_init_start
              run: |
                  echo "Starting linter"

            # #
            #   Initialize â€º Checkout
            # #

            - name: 'â˜‘ï¸ Checkout'
              id: task_init_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Initialize â€º Setup Node
            # #

            - name: 'âš™ï¸ Setup Node'
              id: task_init_node_setup
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            # #
            #   Initialize â€º Node Clean Install
            # #

            - name: 'ðŸ•› NPM â€º Clean Install'
              id: task_init_npm_install
              run: |
                  npm ci

            # #
            #   Initialize â€º Get Package Version
            # #

            - name: 'ðŸ‘ï¸â€ðŸ—¨ï¸ Get Package Version'
              id: task_init_pkg_ver_get
              run: |
                  VER=$(cat package.json | jq -r '.version')
                  echo "PACKAGE_VERSION=$VER" >> $GITHUB_OUTPUT

            - name: 'ðŸ‘ï¸â€ðŸ—¨ï¸ Found KeeWeb v${{ steps.task_init_pkg_ver_get.outputs.PACKAGE_VERSION }}'
              id: task_init_pkg_ver_print
              run: |
                  echo Found KeeWeb ${{ steps.task_init_pkg_ver_get.outputs.PACKAGE_VERSION }}

            # #
            #   Initialize â€º generate guid and uuid
            # #

            - name: 'ðŸªª .ENV â€º Generate'
              id: task_init_pkg_env_generate
              continue-on-error: true
              run: |
                  npm run keeweb:generate

            # #
            #   Initialize â€º assign guid and uuid to env variable
            # #

            - name: 'ðŸªª .ENV â€º Get'
              id: task_init_dotenv_get
              if: steps.task_init_pkg_env_generate.outcome == 'success'
              uses: falti/dotenv-action@v1

            # #
            #   Initialize â€º read back guid and uuid
            # #

            - name: 'ðŸªª .ENV â€º Read'
              id: task_init_dotenv_print
              if: steps.task_init_pkg_env_generate.outcome == 'success'
              run: |
                  echo "VER: ${{ steps.task_init_dotenv_get.outputs.VERSION }}"
                  echo "GUID: ${{ steps.task_init_dotenv_get.outputs.GUID }}"
                  echo "UUID: ${{ steps.task_init_dotenv_get.outputs.UUID }}"

    # #
    #   Job â€º Lint
    # #

    job-lint:
        name: >-
            ðŸ“š Lint
        runs-on: ubuntu-latest
        needs: [job-initialize]
        env:
            PACKAGE_VERSION: ${{ needs.job-initialize.outputs.package_version }}
            GUID: ${{ needs.job-initialize.outputs.guid }}
            UUID: ${{ needs.job-initialize.outputs.uuid }}
        outputs:
            lint_success: ${{ steps.task_lint_npm_lint.outcome }}
        steps:

            # #
            #   Lint â€º Checkout
            # #

            - name: 'â˜‘ï¸ Checkout'
              id: task_lint_checkout
              uses: actions/checkout@v4

            # #
            #   Lint â€º Setup Node
            # #

            - name: 'âš™ï¸ Setup Node'
              id: task_lint_node_setup
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            # #
            #   Lint â€º NPM Install
            # #

            - name: 'ðŸ•› NPM â€º Clean Install'
              id: task_lint_npm_install
              run: |
                  npm ci

            # #
            #   Lint â€º Run
            # #

            - name: 'ðŸ•ž NPM â€º Lint'
              id: task_lint_npm_lint
              run: |
                  npm run lint

            # #
            #   Lint â€º Generate Coverage
            # #

            - name: 'ðŸ•˜ NPM â€º Coverage'
              id: task_lint_npm_coverage
              if: always()
              run: |
                  npm run coverage

            # #
            #   Lint â€º Upload Coverage to Codecov
            # #

            - name: 'ðŸ“ Upload Coverage Reports â€º Codecov'
              id: task_lint_codecov_upload
              if: steps.task_lint_npm_coverage.outcome == 'success'
              uses: codecov/codecov-action@v4.0.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: keeweb/keeweb

    # #
    #   Job â€º Test
    # #

    job-test:
        name: >-
            ðŸ§ª Tests
        runs-on: ubuntu-latest
        needs: [job-initialize]
        env:
            PACKAGE_VERSION: ${{ needs.job-initialize.outputs.package_version }}
        outputs:
            test_success: ${{ steps.task_test_npm_test.outcome }}
        steps:

            # #
            #   Test â€º Fix Line Endings
            # #

            - name: 'ðŸ›’ Fix Git Checkout Line Endings'
              id: task_test_git_fixlines
              run: |
                  git config --global core.autocrlf input

            # #
            #   Test â€º Checkout
            # #

            - name: 'â˜‘ï¸ Checkout'
              id: task_test_checkout
              uses: actions/checkout@v4

            # #
            #   Test â€º Setup Node
            # #

            - name: 'âš™ï¸ Setup Node'
              id: task_test_node_setup
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            # #
            #   Test â€º NPM Install
            # #

            - name: 'ðŸ•› NPM â€º Clean Install'
              id: task_test_npm_install
              run: |
                  npm ci

            # #
            #   Test â€º Run
            # #

            - name: 'ðŸ•˜ NPM â€º Test'
              id: task_test_npm_test
              run: |
                  npm run test

    # #
    #   Job â€º Complete
    # #

    job-complete-run:
        name: >-
            âœ… Complete
        runs-on: ubuntu-latest
        needs: [job-initialize, job-lint, job-test]
        env:
            PACKAGE_VERSION: ${{ needs.job-initialize.outputs.package_version }}
            TEST_SUCCESS: ${{ needs.job-test.outputs.test_success }}
            LINT_SUCCESS: ${{ needs.job-lint.outputs.lint_success }}
            GUID: ${{ needs.job-initialize.outputs.guid }}
            UUID: ${{ needs.job-initialize.outputs.uuid }}
        steps:

            # #
            #   Complete â€º Get publish timestamp
            # #

            - name: 'ðŸ•› Get Timestamp'
              id: task_tests_complete_timestamp
              run: |
                  echo "NOW=$(date +'%m-%d-%Y %H:%M:%S')" >> $GITHUB_ENV

            # #
            #   Complete â€º Debug Print
            # #

            - name: "ðŸ”– Output"
              run: |
                echo "LINT_SUCCESS: ${{ env.LINT_SUCCESS }}"
                echo "TEST_SUCCESS: ${{ env.TEST_SUCCESS }}"

            # #
            #   Complete â€º Summary of publish
            # #

            - name: 'ðŸ†— Summary: ${{ env.NOW }} - ${{ env.PACKAGE_VERSION }}'
              id: task_tests_complete_summary
              shell: bash
              run: |
                  echo ""
                  echo ""
                  echo "| File                            | Result                                                          |" >> $GITHUB_STEP_SUMMARY
                  echo "| ------------------------------- | -----------------------                                         |" >> $GITHUB_STEP_SUMMARY
                  echo "| **Project**                     | ${{ env.PLUGIN_NAME || github.event.inputs.PLUGIN_NAME }}       |" >> $GITHUB_STEP_SUMMARY
                  echo "| **Deploy Time**                 | ${{ env.NOW }}                                                  |" >> $GITHUB_STEP_SUMMARY
                  echo "| **GUID**                        | ${{ env.GUID }}                                                 |" >> $GITHUB_STEP_SUMMARY
                  echo "| **UUID**                        | ${{ env.UUID }}                                                 |" >> $GITHUB_STEP_SUMMARY
                  if [ ${{ env.LINT_SUCCESS }} == 'true' ] || [ ${{ env.LINT_SUCCESS }} == 'success' ]; then
                      echo "| **Lint Results**            | âœ”ï¸                                                              |" >> $GITHUB_STEP_SUMMARY
                  else
                      echo "| **Lint Results**            | âŒ                                                              |" >> $GITHUB_STEP_SUMMARY
                  fi
                  if [ ${{ env.TEST_SUCCESS }} == 'true' ] || [ ${{ env.TEST_SUCCESS }} == 'success' ]; then
                      echo "| **Test Results**            | âœ”ï¸                                                              |" >> $GITHUB_STEP_SUMMARY
                  else
                      echo "| **Test Results**            | âŒ                                                              |" >> $GITHUB_STEP_SUMMARY
                  fi