# #
#   @type               github workflow
#   @author             Aetherinox
#   @url                https://github.com/Aetherinox
#   @usage              deploys docker container to github
#   @secrets            secrets.ADMINSERV_GPG_KEY_ASC                   gpg private key (armored) | BEGIN PGP PRIVATE KEY BLOCK
#                       secrets.ADMINSERV_GPG_PASSPHRASE                gpg private key passphrase
#                       secrets.IMAGE_GHCR_TOKEN                        github personal access token (classic) with package:write permission
# #

name: "üì¶ Deploy ‚Ä∫ Docker ‚Ä∫ Github"
run-name: "üì¶ Deploy ‚Ä∫ Docker ‚Ä∫ Github"

# #
#   Triggers
# #

on:

    # #
    #   Trigger ‚Ä∫ Workflow Dispatch
    #
    #   If any values are not provided, will use fallback env variable
    # #

    workflow_dispatch:
        inputs:

            # #
            #   Image Name
            #
            #   used in github image path
            #       ghcr.io/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
            # #

            IMAGE_NAME:
                description:  "üì¶ Image Name"
                required:     true
                default:      'keeweb'
                type:         string

            # #
            #   Image Author
            #
            #   used in github image path
            #       ghcr.io/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
            # #

            IMAGE_AUTHOR:
                description:  "ü™™ Image Author"
                required:     true
                default:      'keeweb'
                type:         string

            # #
            #   Image Version
            #
            #   used to create new release tag, and add version to docker image name
            # #

            IMAGE_VERSION:
                description:  "üè∑Ô∏è Image Version"
                required:     true
                default:      '1.19.0'
                type:         string

            # #
            #   Image ghcr username
            #
            #   this is the user to sign into ghcr as.
            # #

            IMAGE_GHCR_USERNAME:
                description:  "ü™™ ghcr.io Username"
                required:     true
                default:      'keeweb'
                type:         string

            # #
            #   true:     runs all actions, even ones not scheduled
            #   false:    only scheduled tasks will run
            # #

            PRINT_ONLY:
                description:  "üìë Print Debugs Only"
                required:     true
                default:      false
                type:         boolean

            # #
            #   ENABLE:       released version will be marked as beta and receive beta tag for docker
            #   DISABLE:      release version will be marked as stable / normal release
            # #

            DEV_RELEASE:
                description:  "üß™ Development Release"
                required:     true
                default:      false
                type:         boolean

    # #
    #   Trigger ‚Ä∫ Push
    # #

    push:
        tags:
            - '*'

# #
#   Environment Vars
# #

env:
    IMAGE_NAME:           ${{ github.event.inputs.IMAGE_NAME || 'keeweb' }}
    IMAGE_AUTHOR:         ${{ github.event.inputs.IMAGE_AUTHOR || 'keeweb' }}
    IMAGE_VERSION:        ${{ github.event.inputs.IMAGE_VERSION || '1.19.0' }}
    IMAGE_GHCR_USERNAME:  ${{ github.event.inputs.IMAGE_GHCR_USERNAME || 'keeweb' }}
    BOT_NAME_1:           EuropaServ
    BOT_NAME_DEPENDABOT:  dependabot[bot]
    
# #
#   Jobs
#
#   The way pushed docker containers on Github work, the most recent image built goes at the top.
#   We will use the order below which builds the :latest image last so that it appears at the very
#   top of the packages page.
# #

jobs:

    # #
    #   Job ‚Ä∫ Create Tag
    # #

    job-docker-release-tags-create:
        name: >-
          üì¶ Release ‚Ä∫ Create Tag
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            attestations: write
            id-token: write
        steps:

            # #
            #   Release ‚Ä∫ Tags ‚Ä∫ Start
            # #

            - name: "‚úÖ Start"
              id: task_ctags_start
              run: |
                  echo "Creating Tag"

            # #
            #   Release ‚Ä∫ Tags ‚Ä∫ Checkout
            # #

            - name: "‚òëÔ∏è Checkout"
              id: task_ctags_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Release ‚Ä∫ Tags ‚Ä∫ Check Permissions
            # #

            - name: 'Check Permissions'
              run: |
                  find ./ -name 'run' -exec chmod 755 {} \;
                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                  if [ -n "${WRONG_PERM}" ]; then
                      for i in ${WRONG_PERM}; do
                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                      done
                      exit 1
                  else
                      echo "**** Executable permissions are OK ****"
                  fi

            # #
            #   Release ‚Ä∫ Tags ‚Ä∫ Create Tag
            #
            #   only called in dispatch mode
            # #

            - uses: rickstaa/action-create-tag@v1
              id: task_ctags_create
              if: ( github.event_name != 'workflow_dispatch' && inputs.PRINT_ONLY == false )
              with:
                  tag: "${{ env.IMAGE_VERSION }}"
                  tag_exists_error: false
                  message: '${{ env.IMAGE_NAME }}-${{ env.IMAGE_VERSION }}'
                  gpg_private_key: ${{ secrets.ADMINSERV_GPG_KEY_ASC }}
                  gpg_passphrase: ${{ secrets.ADMINSERV_GPG_PASSPHRASE }}

    # #
    #   Job ‚Ä∫ Docker Release ‚Ä∫ Github ‚Ä∫ Arm64
    # #

    job-docker-release-github-arm64:
        name: >-
          üì¶ Release ‚Ä∫ Github ‚Ä∫ Arm64
        runs-on: ubuntu-latest
        needs: [ job-docker-release-tags-create ]
        permissions:
            contents: write
            packages: write
            attestations: write
            id-token: write
        steps:

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Start ‚Ä∫ Arm64
            # #

            - name: "‚úÖ Start"
              id: task_release_gh_start
              run: |
                  echo "Starting Github Docker arm64"

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Checkout ‚Ä∫ Arm64
            # #

            - name: "‚òëÔ∏è Checkout"
              id: task_release_gh_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Check Permissions
            # #

            - name: 'Check Permissions'
              run: |
                  find ./ -name 'run' -exec chmod 755 {} \;
                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                  if [ -n "${WRONG_PERM}" ]; then
                      for i in ${WRONG_PERM}; do
                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                      done
                      exit 1
                  else
                      echo "**** Executable permissions are OK ****"
                  fi

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ QEMU ‚Ä∫ Arm64
            # #

            - name: "‚öôÔ∏è Set up QEMU"
              id: task_release_gh_qemu
              uses: docker/setup-qemu-action@v3

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Setup BuildX ‚Ä∫ Arm64
            # #

            - name: "‚öôÔ∏è Setup Buildx"
              id: task_release_gh_buildx
              uses: docker/setup-buildx-action@v3
              with:
                  version: latest
                  driver-opts: 'image=moby/buildkit:v0.10.5'

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Registry Login ‚Ä∫ Arm64
            # #

            - name: "‚öôÔ∏è Login to Github"
              id: task_release_gh_registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ env.IMAGE_GHCR_USERNAME }}
                  password: ${{ secrets.IMAGE_GHCR_TOKEN }}

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Meta ‚Ä∫ Arm64
            # #

            - name: "üî® Github: Meta - Arm64"
              id: task_release_gh_meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
                  tags: |
                      #  latest no
                      type=raw,value=latest,enable=false
                      #  dispatch       add x1.x.x-arm64
                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == false }},priority=300,prefix=,suffix=-arm64,value=${{ env.IMAGE_VERSION }}
                      #  dispatch       add arm64-development
                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == true }},priority=300,prefix=,suffix=-development,value=arm64
                      #  tag            add tag-arm64
                      type=ref,enable=${{ github.event_name == 'pull_request' || github.event_name == 'push' }},priority=600,prefix=,suffix=-arm64,event=tag
                  flavor: |
                      latest=false

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Debug ‚Ä∫ Arm64
            # #

            - name: "ü™™ Debug ‚Ä∫ Print"
              id: task_release_gh_print
              run: |
                  echo "registry ............. Github"
                  echo "github.actor.......... ${{ github.actor }}"
                  echo "github.ref ........... ${{ github.ref }}"
                  echo "github.event_name .... ${{ github.event_name }}"
                  echo "inputs.PRINT_ONLY .... ${{ inputs.PRINT_ONLY }}"
                  echo "env.AUTHOR ........... ${{ env.IMAGE_AUTHOR }}"
                  echo "tags ................. ${{ steps.task_release_gh_meta.outputs.tags }}"
                  echo "labels ............... ${{ steps.task_release_gh_meta.outputs.labels }}"

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Build and Push ‚Ä∫ Arm64
            # #

            - name: "üì¶ Build & Push (linux/arm64)"
              id: task_release_gh_push
              uses: docker/build-push-action@v6
              if: ( github.event_name == 'workflow_dispatch' && inputs.PRINT_ONLY == false ) || ( github.event_name == 'push' )
              with:
                  context: .
                  file: Dockerfile.aarch64
                  platforms: linux/arm64
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.task_release_gh_meta.outputs.tags }}
                  labels: ${{ steps.task_release_gh_meta.outputs.labels }}

    # #
    #   Job ‚Ä∫ Docker Release ‚Ä∫ Github ‚Ä∫ Amd64
    # #

    job-docker-release-github-amd64:
        name: >-
          üì¶ Release ‚Ä∫ Github ‚Ä∫ Amd64
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            attestations: write
            id-token: write
        needs: [ job-docker-release-tags-create, job-docker-release-github-arm64 ]
        steps:

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Start ‚Ä∫ Amd64
            # #

            - name: "‚úÖ Start"
              id: task_release_gh_start
              run: |
                  echo "Starting Github docker release"

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Checkout ‚Ä∫ Amd64
            # #

            - name: "‚òëÔ∏è Checkout"
              id: task_release_gh_checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Check Permissions
            # #

            - name: 'Check Permissions'
              run: |
                  find ./ -name 'run' -exec chmod 755 {} \;
                  WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                  if [ -n "${WRONG_PERM}" ]; then
                      for i in ${WRONG_PERM}; do
                      echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                      done
                      exit 1
                  else
                      echo "**** Executable permissions are OK ****"
                  fi

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ QEMU ‚Ä∫ Amd64
            # #

            - name: "‚öôÔ∏è Set up QEMU"
              id: task_release_gh_qemu
              uses: docker/setup-qemu-action@v3

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Setup BuildX ‚Ä∫ Amd64
            # #

            - name: "‚öôÔ∏è Setup Buildx"
              id: task_release_gh_buildx
              uses: docker/setup-buildx-action@v3
              with:
                  version: latest
                  driver-opts: 'image=moby/buildkit:v0.10.5'

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Registry Login ‚Ä∫ Amd64
            # #

            - name: "‚öôÔ∏è Login to Github"
              id: task_release_gh_registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ env.IMAGE_GHCR_USERNAME }}
                  password: ${{ secrets.IMAGE_GHCR_TOKEN }}

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Meta ‚Ä∫ Amd64
            # #

            - name: "üî® Github: Meta - Amd64"
              id: task_release_gh_meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
                  tags: |
                      #  latest yes
                      type=raw,value=latest,enable=${{ !inputs.DEV_RELEASE }}
                      #  dispatch       add x1.x.x-amd64
                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == false }},priority=300,prefix=,suffix=-amd64,value=${{ env.IMAGE_VERSION }}
                      #  dispatch       add amd64-development
                      type=raw,enable=${{ github.event_name == 'workflow_dispatch' && inputs.DEV_RELEASE == true }},priority=300,prefix=,suffix=-development,value=amd64
                      #  tag            add tag-arm64
                      type=ref,enable=${{ github.event_name == 'pull_request' || github.event_name == 'push'}},priority=600,prefix=,suffix=-amd64,event=tag
                      #  add development tag
                      type=raw,enable=${{ inputs.DEV_RELEASE }},priority=400,prefix=,suffix=,value=development
                  flavor: |
                      latest=${{ !inputs.DEV_RELEASE }}

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Debug ‚Ä∫ Amd64
            # #

            - name: "ü™™ Debug ‚Ä∫ Print"
              id: task_release_gh_print
              run: |
                  echo "registry ............. Github"
                  echo "github.actor.......... ${{ github.actor }}"
                  echo "github.ref ........... ${{ github.ref }}"
                  echo "github.event_name .... ${{ github.event_name }}"
                  echo "inputs.PRINT_ONLY .... ${{ inputs.PRINT_ONLY }}"
                  echo "env.AUTHOR ........... ${{ env.IMAGE_AUTHOR }}"
                  echo "tags ................. ${{ steps.task_release_gh_meta.outputs.tags }}"
                  echo "labels ............... ${{ steps.task_release_gh_meta.outputs.labels }}"

            # #
            #   Release ‚Ä∫ Github ‚Ä∫ Build and Push ‚Ä∫ Amd64
            # #

            - name: "üì¶ Build & Push (linux/amd64)"
              id: task_release_gh_push
              uses: docker/build-push-action@v6
              if: ( github.event_name == 'workflow_dispatch' && inputs.PRINT_ONLY == false ) || ( github.event_name == 'push' )
              with:
                  context: .
                  file: Dockerfile
                  platforms: linux/amd64
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: ${{ steps.task_release_gh_meta.outputs.tags }}
                  labels: ${{ steps.task_release_gh_meta.outputs.labels }}
