# #
#   @type               github workflow
#   @author             Aetherinox
#   @url                https://github.com/Aetherinox
#   @usage              clears all history in your deployments.
#                       edit the 'environment:' to determine which deployment to keep clean
#                           - can be ran manually
#
#   @secrets            secrets.SELF_TOKEN_CL                   Github Access Token (Classic)
# #

name: "‚öôÔ∏è Deploy ‚Ä∫ Clean"
run-name: "‚öôÔ∏è Deploy ‚Ä∫ Clean"

# #
#   triggers
# #

on:
    workflow_dispatch:

# #
#   environment variables
# #

env:
    BOT_NAME_1:           EuropaServ
    BOT_NAME_DEPENDABOT:  dependabot[bot]
    LABELS_JSON: |
      [
          { "name": "AC ‚Ä∫ Changes Made",           "color": "8F1784", "description": "Requested changes have been made and are pending a re-scan" },
          { "name": "AC ‚Ä∫ Changes Required",       "color": "8F1784", "description": "Requires changes to be made to the package before being accepted" },
          { "name": "AC ‚Ä∫ Failed",                 "color": "a61f2d", "description": "Autocheck failed to run through a complete cycle, requires investigation" },
          { "name": "AC ‚Ä∫ Needs Rebase",           "color": "8F1784", "description": "Due to the permissions on the requesting repo, this pull request must be rebased by the author" },
          { "name": "AC ‚Ä∫ Passed",                 "color": "146b4a", "description": "Ready to be reviewed" },
          { "name": "AC ‚Ä∫ Review Required",        "color": "8F1784", "description": "PR needs to be reviewed by another person, after the requested changes have been made" },
          { "name": "AC ‚Ä∫ Security Warning",       "color": "761620", "description": "Does not conform to developer policies, or includes potentially dangerous code" },
          { "name": "AC ‚Ä∫ Skipped Scan",           "color": "8F1784", "description": "Author has skipped code scan" },
          { "name": "Status êÑÇ Duplicate",          "color": "75536b", "description": "Issue or pull request already exists" },
          { "name": "Status êÑÇ Accepted",            "color": "2e7539", "description": "This pull request has been accepted" },
          { "name": "Status êÑÇ Autoclosed",          "color": "3E0915", "description": "Originally stale and was autoclosed for no activity" },
          { "name": "Status êÑÇ Denied",              "color": "ba4058", "description": "Pull request has been denied" },
          { "name": "Status êÑÇ Locked",              "color": "550F45", "description": "Automatically locked by AdminServ for a prolonged period of inactivity" },
          { "name": "Status êÑÇ Need Info",           "color": "2E3C4C", "description": "Not enough information to resolve" },
          { "name": "Status êÑÇ No Action",           "color": "030406", "description": "Closed without any action being taken" },
          { "name": "Status êÑÇ Pending",             "color": "984b12", "description": "Pending pull request" },
          { "name": "Status êÑÇ Released",            "color": "1b6626", "description": "Issues or PR has been implemented and is now live" },
          { "name": "Status êÑÇ Reopened",            "color": "8a6f14", "description": "A previously closed PR which has been re-opened" },
          { "name": "Status êÑÇ Review",              "color": "9e1451", "description": "Currently pending review" },
          { "name": "Status êÑÇ Stale",               "color": "928282", "description": "Has not had any activity in over 30 days" },
          { "name": "Type ‚ó¶ Bug",                   "color": "9a2c2c", "description": "Something isn't working" },
          { "name": "Type ‚ó¶ Dependency",            "color": "243759", "description": "Item is associated to dependency" },
          { "name": "Type ‚ó¶ Docs",                  "color": "0e588d", "description": "Improvements or modifications to docs" },
          { "name": "Type ‚ó¶ Feature",               "color": "3c4e93", "description": "Feature request" },
          { "name": "Type ‚ó¶ Git Action",            "color": "030406", "description": "GitHub Action / workflow" },
          { "name": "Type ‚ó¶ Pull Request",          "color": "8F1784", "description": "Normal pull request" },
          { "name": "Type ‚ó¶ Roadmap",               "color": "8F1784", "description": "Feature or bug currently planned for implementation" },
          { "name": "Type ‚ó¶ Internal",              "color": "A51994", "description": "Assigned items are for internal developer use" },
          { "name": "Build ‚ó¶ Desktop",              "color": "c7ca4a", "description": "Specific to desktop" },
          { "name": "Build ‚ó¶ Linux",                "color": "c7ca4a", "description": "Specific to Linux" },
          { "name": "Build ‚ó¶ MacOS",                "color": "c7ca4a", "description": "Specific to MacOS" },
          { "name": "Build ‚ó¶ Mobile",               "color": "c7ca4a", "description": "Specific to mobile" },
          { "name": "Build ‚ó¶ Web",                  "color": "c7ca4a", "description": "Specific to web" },
          { "name": "Build ‚ó¶ Windows",              "color": "c7ca4a", "description": "Specific to Windows" },
          { "name": "‚Ä∫ API",                        "color": "F99B50", "description": "Plugin API, CLI, browser JS API" },
          { "name": "‚Ä∫ Auto-type",                  "color": "9141E0", "description": "Auto-type functionality in desktop apps" },
          { "name": "‚Ä∫ Browser",                    "color": "9141E0", "description": "Browser plugins and passing data to <=> from app" },
          { "name": "‚Ä∫ Customization",              "color": "E3F0FC", "description": "Customizations: plugins, themes, configs" },
          { "name": "‚Ä∫ Design",                     "color": "FA70DE", "description": "Design related queries" },
          { "name": "‚Ä∫ Dist",                       "color": "FA70DE", "description": "Installers and other forms of software distribution" },
          { "name": "‚Ä∫ Enterprise",                 "color": "11447a", "description": "Issues about collaboration, administration, and so on" },
          { "name": "‚Ä∫ Hardware",                   "color": "5a7503", "description": "YubiKey, other tokens, biometrics" },
          { "name": "‚Ä∫ Import/Export",              "color": "F5FFCC", "description": "Import from and export to different file formats" },
          { "name": "‚Ä∫ Improvement",                "color": "185c98", "description": "Enhance an existing feature" },
          { "name": "‚Ä∫ Performance",                "color": "006b75", "description": "Web and desktop performance issues" },
          { "name": "‚Ä∫ Plugin Request",             "color": "FCE9CA", "description": "Requested changes should be implemented as a plugin" },
          { "name": "‚Ä∫ Security",                   "color": "F75D39", "description": "Security issues" },
          { "name": "‚Ä∫ Self-Hosting",               "color": "fad8c7", "description": "Self-hosting installations and configs" },
          { "name": "‚Ä∫ Storage",                    "color": "5319e7", "description": "Storage providers: Dropbox, Google, WebDAV, etc." },
          { "name": "‚Ä∫ Updater",                    "color": "1BADDE", "description": "Auto-updater issues" },
          { "name": "‚Ä∫ UX",                         "color": "1BADDE", "description": "UX and usability" },
          { "name": "‚Ä∫ Website",                    "color": "fef2c0", "description": "Website related issues" },
          { "name": "‚ö† Urgent",                     "color": "a8740e", "description": "Requires urgent attention" },
          { "name": "‚ö† Announcement",               "color": "DB4712", "description": "Announcements" },
          { "name": "üì∞ Progress Report",           "color": "392297", "description": "Development updates" },
          { "name": "üì¶ Release",                   "color": "277542", "description": "Release announcements" },
          { "name": "‚úîÔ∏è Poll",                      "color": "972255", "description": "Community polls" },
          { "name": "‚ùî Question",                  "color": "FFFFFF", "description": "All questions" }
      ]

# #
#   jobs
# #

jobs:
    cleanup:
        runs-on: ubuntu-latest
        permissions: write-all
  
        steps:
            - name: >-
                ‚öôÔ∏è Deployments ‚Ä∫ Clean
              uses: Aetherinox/delete-deploy-env-action@v3
              with:
                  token: ${{ secrets.SELF_TOKEN_CL }}
                  environment: orion
                  onlyRemoveDeployments: true
                  delay: "1000"